[2024-08-15T14:39:04.194+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-15T14:39:04.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres.csv_to_stg manual__2024-08-15T14:38:57.628704+00:00 [queued]>
[2024-08-15T14:39:04.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres.csv_to_stg manual__2024-08-15T14:38:57.628704+00:00 [queued]>
[2024-08-15T14:39:04.232+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-15T14:39:04.250+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): csv_to_stg> on 2024-08-15 14:38:57.628704+00:00
[2024-08-15T14:39:04.258+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-15T14:39:04.260+0000] {standard_task_runner.py:64} INFO - Started process 1122 to run task
[2024-08-15T14:39:04.260+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres', 'csv_to_stg', 'manual__2024-08-15T14:38:57.628704+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmppeh2ww5d']
[2024-08-15T14:39:04.261+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask csv_to_stg
[2024-08-15T14:39:04.316+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres.csv_to_stg manual__2024-08-15T14:38:57.628704+00:00 [running]> on host 05857a123f31
[2024-08-15T14:39:04.429+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gena' AIRFLOW_CTX_DAG_ID='csv_to_postgres' AIRFLOW_CTX_TASK_ID='csv_to_stg' AIRFLOW_CTX_EXECUTION_DATE='2024-08-15T14:38:57.628704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-15T14:38:57.628704+00:00'
[2024-08-15T14:39:04.431+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-15T14:39:04.433+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-15T14:39:04.434+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/csv_to_stg.py", line 28, in csv_to_stg
    pg_hook = PostgresHook(postgres_conn_id=conn_id)
              ^^^^^^^^^^^^
NameError: name 'PostgresHook' is not defined
[2024-08-15T14:39:04.453+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres, task_id=csv_to_stg, run_id=manual__2024-08-15T14:38:57.628704+00:00, execution_date=20240815T143857, start_date=20240815T143904, end_date=20240815T143904
[2024-08-15T14:39:04.475+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task csv_to_stg (name 'PostgresHook' is not defined; 1122)
[2024-08-15T14:39:04.515+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-15T14:39:04.536+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-15T14:39:04.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
